# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 21, 17, 44, 8, 905991, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
